[pytest]
; Store pytest cache files in tmp/.pytest_cache
cache_dir = tmp/.pytest_cache

; Set default command-line options
addopts = -v -s

; Specify which files Pytest searches for test functions
python_files = test_*.py *_test.py

; Specify which classes Pytest searches for test methods
python_classes = Test*

; Specify which functions Pytest searches for test cases
python_functions = test_*

; Set the test directory path
testpaths = tests